POST http://localhost:8080/posts/1/comments
Content-Type: application/json

{
  "text": "priveeet",
  "accountId": 5
}

#####

GET http://localhost:8080/posts/1/comments

####
DELETE http://localhost:8080/posts/1/comments/2

###

PATCH http://localhost:8080/posts/1/comments/2
Content-Type: application/json

{
  "postId": 1,
  "text": "helllll",
  "accountId": 5
}