<#import "/spring.ftl" as spring>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>

<form method="post">
    <input name="username" type="text" placeholder="username">
    <input name="password" type="password" placeholder="password">
    <div>
        <button type="submit">Зарегистрироваться</button>
        <a href="">Уже есть аккаунт</a>
    </div>
</form>
</body>
</html>